# Trident Version configuration file

set(PACKAGE_VERSION_MAJOR 1)  # major version if provided, else 0
set(PACKAGE_VERSION_MINOR 0)  # minor version if provided, else 0
set(PACKAGE_VERSION_PATCH 0)  # patch version if provided, else 0
set(PACKAGE_VERSION_TWEAK 1)  # tweak version if provided, else 0

set(PACKAGE_VERSION "${PACKAGE_VERSION_MAJOR}.${PACKAGE_VERSION_MINOR}.${PACKAGE_VERSION_PATCH}.${PACKAGE_VERSION_TWEAK}")

if(PACKAGE_FIND_VERSION_COUNT LESS 2) 
  set(PACKAGE_VERSION_UNSUITABLE true)
elseif(PACKAGE_VERSION_MAJOR EQUAL PACKAGE_FIND_VERSION_MAJOR AND PACKAGE_VERSION_MINOR EQUAL PACKAGE_FIND_VERSION_MINOR AND PACKAGE_VERSION_PATCH EQUAL PACKAGE_FIND_VERSION_PATCH AND PACKAGE_VERSION_TWEAK EQUAL PACKAGE_FIND_VERSION_TWEAK)
  set(PACKAGE_VERSION_EXACT true)
elseif(PACKAGE_VERSION_MAJOR EQUAL PACKAGE_FIND_VERSION_MAJOR AND PACKAGE_VERSION_MINOR EQUAL PACKAGE_FIND_VERSION_MINOR)
  set(PACKAGE_VERSION_COMPATIBLE true)
endif()

message(STATUS "FOUND trident --> VERSION ${PACKAGE_VERSION}")
