/**
 * Author: Tobias Appl <tobias.appl@gmail.com>
 */

#ifndef TRIDENT_CONFIG_H
#define TRIDENT_CONFIG_H

#cmakedefine TRIDENT_PLATFORM @TRIDENT_PLATFORM@

#cmakedefine TRIDENT_PIN_COUNT @TRIDENT_PIN_COUNT@

/*** Simulation IPC ***/
#cmakedefine TRIDENT_SIMULATION_IPC_DUMMY_FILE_FOLDER "@TRIDENT_SIMULATION_IPC_DUMMY_FILE_FOLDER@"

#cmakedefine TRIDENT_SIMULATION_IPC_WIRE_CONFIG "@TRIDENT_SIMULATION_IPC_WIRE_CONFIG@"

/*** LOGGING ***/
#cmakedefine TRIDENT_LOGGING_INFO

#cmakedefine TRIDENT_LOGGING_ERROR

#cmakedefine TRIDENT_LOGGING_FILE "@TRIDENT_LOGGING_FILE@"

#cmakedefine TRIDENT_LOGGING_LAYER0_ENABLED

#cmakedefine TRIDENT_LOGGING_LAYER1_ENABLED

#cmakedefine TRIDENT_LOGGING_LAYER2_ENABLED

#cmakedefine TRIDENT_LOGGING_APPLICATION_ENABLED

#endif // TRIDENT_CONFIG_H
