/**
 * Author: Tobias Appl <tobias.appl@gmail.com>
 */

#ifndef ERRNO_H
#define ERRNO_H

typedef enum {
    ERRNO_UNDEFINED = -1,
    ERRNO_NO_ERROR = 0,
    ERRNO_FUNCTION_ARGUMENT_VALUES = 1,
    ERRNO_PIN_INIT = 2,
    ERRNO_PIN_IN_INIT = 3,
    ERRNO_PIN_OUT_INIT = 4,
    ERRNO_PIN_NUMBER_INVALID = 5,
    ERRNO_PIN_RESERVED = 6,
    ERRNO_PIN_NOT_SET = 18,
    ERRNO_PIN_FILE_DESCRIPTOR = 15,
    ERRNO_PIN_READ = 38,
    ERRNO_MAX_CHANNELS_REACHED = 7,
    ERRNO_CHANNEL_INIT = 8,
    ERRNO_CHANNEL_IO_UNDEFINED = 9,
    ERRNO_CHANNEL_DIRECTION = 10,
    ERRNO_CHANNEL_IDX = 11,
    ERRNO_CHANNEL_NOT_INITIALIZED = 27,
    ERRNO_OUT_TRANSMISSION = 12,
    ERRNO_IN_TRANSMISSION = 13,
    ERRNO_SENDER_RETURN_VALUE = 14,
    ERRNO_FSM_STATE = 16,
    ERRNO_TRIDENT_PREREQUISITES = 17,
    ERRNO_BARRIER_FSM = 19,
    ERRNO_RESET_PIN_NR_INVALID = 20,
    ERRNO_RESET_PIN_NOT_SET = 22,
    ERRNO_RESET_RESPONSE_PIN_INVALID = 21,
    ERRNO_RESET_RESPONSE_PIN_NOT_SET = 23,
    ERRNO_RESET_OPERATION_FUNCTION_ERROR = 39,
    ERRNO_TRANSMISSION_TERMINATION_RX = 24,
    ERRNO_TRANSMISSION_TERMINATION_TX = 25,
    ERRNO_TRANSMISSION_BIT_WIDTH = 26,
    ERRNO_SIMULATION_CONNECTION_THREAD = 28,
    ERRNO_SIMULATION_PIN_THREAD_NOT_OPEN = 29,
    ERRNO_SIMULATION_FIFO_FD_INVALID = 30,
    ERRNO_SIMULATION_WRITE_FIFO_ERROR = 31,
    ERRNO_SIMULATION_IPC_CONFIG_FILE = 32,
    ERRNO_SIMULATION_IPC_CONFIG_FILE_PARSING = 33,
    ERRNO_SIMULATION_IPC_CONNECTION_THREAD = 34,
    ERRNO_SIMULATION_IPC_PIPE_WRITER = 35,
    ERRNO_SIMULATION_IPC_SHARED_MEMORY_ACCESS = 36,
    ERRNO_SIMULATION_IPC_SHARED_MEMORY_VALUE = 37,
    ERRNO_COMMUNICATION_EXECUTION_THREAD_WAIT = 40,
    ERRNO_COMMUNICATION_EXECUTION_THREAD_MANAGEMENT = 41,
    ERRNO_COMMUNICATION_WRITE_BUFFER_LENGTH = 42,
    ERRNO_COMMUNICATION_SHARED_MEMORY_ACCESS = 43,
    ERRNO_OBJECT_NOT_ALLOCATED = 44
} ERRNO; //[-1,44]

#endif // ERRNO_H

